language: ruby

cache: bundler

services:
  - postgresql
  - mysql

rvm:
  - 2.4

before_script:
  - cd test/dummy
  - bin/rake db:create
  - bin/rake db:migrate
  - bin/rake db_mysql:create
  - bin/rake db_mysql:migrate
  - bin/rake db_sqlite:create
  - bin/rake db_sqlite:migrate
  - cd ../../

script:
  - bundle exec rubocop
  - bin/test
