language: ruby

cache: bundler

services:
  - postgresql
  - mysql

rvm:
  - 2.5

before_script:
  - cd test/dummy && bin/rake db:create
  - cd test/dummy && bin/rake db_mysql:create

script:
  - bin/test
